### PR TITLE
Add an option to specify size to fetch along with stargz footer

### PR DESCRIPTION
**Pull request by ktock**
In some cases (e.g. when high bandwidth and high latency), 2 roundtrips(for
footer + TOC json) can be a performance overhead on the mount.
This commit mitigates this issue by adding an option to specify the size to
fetch along with the stargz footer. By the option, we can hopefully get the TOC
JSON file + footer in one go, which reduces roundtrips.

This is also one of the TODO consumption indicated in the source code.

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
@bradfitz PTAL?

**Comment by AkihiroSuda** [comment]
@bradfitz Do you still have write access to this repo?

**Comment by bradfitz** [comment]
I do for now. I might lose it in 13 minutes or so, though.

I've asked people to give me (some) access again in the future if a cron job removes me when I leave the company.

**Comment by strigazi** [comment]
@ktock We don't need this anymore? For the stargz snapshotter is see:
```
{"error":"digest of TOC JSON must be passed","key":"default/17/extract-399504542-1kJk sha256:24e86b854ae9f3a8846717b4ab84931d2f1a368ae04542dc73f0347dd3c1484f","level":"debug","msg":"failed to prepare remote snapshot","parent":"default/16/sha256:b5d9eb0b475da4e41df1b58fae4db6011dfc346a00f497569602ce29a16bc827","remote-snapshot-prepared":"false","time":"2020-09-21T07:08:03.401654835Z"}
```

Do you want to follow it in an issue in stargz-snapshotter repo?

**Comment by ktock** [comment]
@strigazi The error seems to be on snapshotter side and unrelated to this thread. Please open the issue on snapshotter repo.

**Pull request closed without merging**
